### PR TITLE
Implement composer.json support, merge in PCP135's NightMode functions.

### PR DESCRIPTION
**Pull request by matthewbaggett**

### CODE REVIEW

**Comment by matthewbaggett** [comment]
You'll need to go to Packagist and submit your project so that it turns up in the index! :)

Cheers! :+1:

**Comment by yasharrashedi** [comment]
I know but I'm currently too busy. I'll do that soon or if someone else do me this favor, it would be highly appreciated.

**Comment by matthewbaggett** [comment]
I have done it for you, as seen here: https://packagist.org/packages/yasharrashedi/limitless-led

But I cannot add the GitHub update hook needed to make it automatically update packagist myself, unless I was given privileges.

**Comment by yasharrashedi** [comment]
Nice! I was waiting for this answer, privileges have been granted, Thank you

**Pull request merged**
